### ISSUE TITLE
export images

### ISSUE THREAD

**Issue by ghost** [CommissarMa/My_CODA#1]

**Comment by CommissarMa** [comment]
my leader says it can not be open source. Sorry.



---Original---

**Comment by ghost** [comment]
@CommissarMa alright, what about the script that export & crops the detected boxes into images?

**Comment by CommissarMa** [comment]
you can reference code in this script.


------------------ 原始邮件 ------------------
发件人: "deepseek"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 中午1:49
收件人: "CommissarMa/My_CODA"<My_CODA@noreply.github.com>;
抄送: "马振伟"<960901625@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CommissarMa/My_CODA] . (#1)




ok, what about the script that export & crops the detected boxes into images?

**Comment by ghost** [comment]
@CommissarMa do you mean `divide_text_region_from_gt.py` ? it only takes `.json` files.
What I meant is a script that crops/ export the detected `x1,y1,x2,y2,x3,y3,x4,y4`.

**Comment by ghost** [comment]
@CommissarMa Can you answer back, 
after detecting boxes, how to exported cropped images from the detected results.
